apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: goapp
spec:
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30089
  type: NodePort